ALTER DATABASE [Vendas] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Vendas] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Vendas] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Vendas] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Vendas] SET ARITHABORT OFF 
GO
ALTER DATABASE [Vendas] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Vendas] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Vendas] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Vendas] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Vendas] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Vendas] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Vendas] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Vendas] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Vendas] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Vendas] SET  ENABLE_BROKER 
GO
ALTER DATABASE [Vendas] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Vendas] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Vendas] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Vendas] SET ALLOW_SNAPSHOT_ISOLATION ON 
GO
ALTER DATABASE [Vendas] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Vendas] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [Vendas] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Vendas] SET RECOVERY FULL 
GO
ALTER DATABASE [Vendas] SET  MULTI_USER 
GO
ALTER DATABASE [Vendas] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Vendas] SET DB_CHAINING OFF 
GO

USE [Vendas]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE Table CategoriaProduto (
	[Codigo] INT NOT NULL,
	[Descricao] VARCHAR(255) NOT NULL,
	[Ativo] BIT CONSTRAINT DF_CategoriaProduto_Ativo DEFAULT(1) NOT NULL,
	[DataCriacao] DATETIME CONSTRAINT DF_CategoriaProduto_DataCriacao DEFAULT(GETDATE()) NOT NULL,
	CONSTRAINT [PK_CategoriaProduto_Codigo] PRIMARY KEY CLUSTERED 
	(
		[Codigo] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO

INSERT INTO CategoriaProduto 
	(Codigo, Descricao)
VALUES
	(1, 'Computadores'),
	(2, 'Impressoras'),
	(3, 'Mesas')
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE Table Produto (
	[ProdutoId] UNIQUEIDENTIFIER CONSTRAINT PK_Produto_ProdutoId DEFAULT(NEWID()) PRIMARY KEY NOT NULL,
	[CategoriaProdutoId] INT NOT NULL,
	[Descricao] VARCHAR(500) NOT NULL,
	[Complemento] VARCHAR(2000) NULL,
	[Valor] DECIMAL(6,2) NOT NULL,
	[Ativo] BIT CONSTRAINT DF_Produto_Ativo DEFAULT(1) NOT NULL,
	[DataCriacao] DATETIME CONSTRAINT DF_Produto_DataCriacao DEFAULT(GETDATE()) NOT NULL,
	CONSTRAINT FK_Produto_CategoriaProduto_CategoriaProdutoId FOREIGN KEY ([CategoriaProdutoId]) REFERENCES CategoriaProduto ([Codigo])
)